# Generated by Django 2.2.14 on 2020-07-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID')),
                ('mailtype', models.CharField(max_length=10, verbose_name='Type')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='ID')),
                ('teletype', models.CharField(max_length=10, verbose_name='Type')),
                ('telenumber', models.IntegerField(verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full name')),
                ('photo_path', models.CharField(max_length=255, verbose_name='Link to avatar')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('birthdate', models.DateField(verbose_name='Birth date')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
    ]
