# Generated by Django 2.2.14 on 2020-07-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='id_user',
        ),
    ]
